### ISSUE TITLE
Sounds and music don't work

### ISSUE THREAD

**Issue by YoshiIsDaBomb** [YTP-Plus/YTPPlusPlus#12]
Recently, I've been testing the application and the outputs don't play any of the sound effects or music. I made sure they were all in their correct formats and use the folders in the Tools option, used all of the .exes (ffmpeg, magick, ffprobe) yet the videos only use the slow down, reverse, speed up effects. How do I fix this?

**Comment by TeamPopplio** [comment]
Do you have a console log? Press F4 and copy the entirety of your console after a render and paste it somewhere like Pastebin or here if you'd like to stick with GitHub.

**Comment by YoshiIsDaBomb** [comment]
I restarted my laptop and one of the renders I did and the music worked. I think all I had to do was that. No problemo.
