### ISSUE TITLE
ImageMagick for Squidward

### ISSUE THREAD

**Issue by YoshiIsDaBomb** [YTP-Plus/YTPPlusPlus#13]
No matter what I do, the Squidward effect never works. When I install it, it goes into the Program Files folder. Is it the wrong folder or did I install the wrong version? I got the HTTP version of "ImageMagick-7.0.10-10-Q16-x64-dll.exe". There's also an option for an FTP version. Should I get that version instead?

**Comment by TeamPopplio** [comment]
Sorry for being absent, can you try to place magick.exe into your Windows PATH?

**Comment by YoshiIsDaBomb** [comment]
Is it the Local Disk > Windows folder? I'll let you know if it works.

**Comment by TeamPopplio** [comment]
No, I mean the Path variable
https://helpdeskgeek.com/windows-10/add-windows-path-environment-variable/

**Comment by DevanWolf** [comment]
Same for me, they are installed correctly, FFmpeg gets this error: Impossible to load "squidwardfad0.png" | weird!

**Comment by KiwifruitDev** [comment]
This repository is no longer supported.
See: [YTP+++](https://github.com/YTP-Plus/YTPPlusPlusPlus)
