### ISSUE TITLE
Can't render video

### ISSUE THREAD

**Issue by DatHeroAndy** [YTP-Plus/YTPPlusPlus#14]
I get this error:

An exception has occured during rendering. Rendering may have not produced a result.

The last exception to occur was:
Input string was not in a correct format.

**Comment by danylopez123** [comment]
I also get the same problem

**Comment by Gmann101** [comment]
Same thing here, what the heck is going on? This makes me immensely frustrated.

**Comment by sdfsdfsdfs1** [comment]
weirdly, this all worked yesterday and now all of a sudden its cracking down and i dunno what the cause is

**Comment by KiwifruitDev** [comment]
This repository is no longer supported.
See: [YTP+++](https://github.com/YTP-Plus/YTPPlusPlusPlus)
