### ISSUE TITLE
Fix outro clips

### ISSUE THREAD

**Issue by jankespro12** [YTP-Plus/YTPPlusPlus#18]
Well, this is not a issue but, maybe outro clips on 3.0 m1 is broken? I wish it was fixed on 3.0 m2

**Comment by TeamPopplio** [comment]
Sorry to hear that you're having this issue.
I'll work to fix this in the next milestone release of 3.0, Milestone 2.
Thank you for bringing this to my attention.

**Comment by fttongithub2** [comment]
how do i get v3 beta?

**Comment by KiwifruitDev** [comment]
v3 of YTP++ is [YTP+++](https://github.com/YTP-Plus/YTPPlusPlusPlus).
