### ISSUE TITLE
Videos aren't working  - YTPPlusPlus

### ISSUE THREAD

**Issue by sdfsdfsdfs1** [YTP-Plus/YTPPlusPlus#24]
I was playing around with the programs yesterday but somehow just today I keep getting this weird error when i put in the same videos i tested out with.

"one or materials added in this batch has a space in its path or file name. While YTP++ will still try to render with the material in question, be aware that this may cause a render failure"

UPDATE: I found a solution to this and for some reason it only reads videos in the downloads and not in anywhere else. Is there also a way to have it read from other folders instead of one?

**Comment by KiwifruitDev** [comment]
This repository is no longer supported.
See: [YTP+++](https://github.com/YTP-Plus/YTPPlusPlusPlus)
