### ISSUE TITLE
Videos don't save properly

### ISSUE THREAD

**Issue by Krafter7** [YTP-Plus/YTPPlusPlus#25]
After rendering and downloading 2 YTPs, the downloads broke and I can't save any of my videos anymore. Whenever I save them, they only show up in the quick view and not in the actual folder I'm saving them to. When I click on them in the quick view, it says the file is moved or missing

**Comment by KiwifruitDev** [comment]
This repository is no longer supported.
See: [YTP+++](https://github.com/YTP-Plus/YTPPlusPlusPlus)
