### ISSUE TITLE
I can't make videos on 3.0 with lua

### ISSUE THREAD

**Issue by jankespro12** [YTP-Plus/YTPPlusPlus#27]
Can you help me? i was trying to make videos with it, but it always fails! look!
![YTP++ 09 03 2023 16_39_06](https://user-images.githubusercontent.com/63473068/224075213-08f45e2c-c195-43d6-8bbf-da23c5e705e3.png)

**Comment by jankespro12** [comment]
Plz help me out

**Comment by KiwifruitDev** [comment]
v3 of YTP++ is [YTP+++](https://github.com/YTP-Plus/YTPPlusPlusPlus).
