### ISSUE TITLE
YTPPlusPlus can't find the VLC directory

### ISSUE THREAD

**Issue by gavinwrivera** [YTP-Plus/YTPPlusPlus#28]
Whenever I try to open YTPPlusPlus, it asks me for my VLC directory, which it can't find for some reason, and then it closes. I got it to open twice, but it wouldn't render the video. How can this be fixed?

**Comment by KiwifruitDev** [comment]
This repository is no longer supported.
See: [YTP+++](https://github.com/YTP-Plus/YTPPlusPlusPlus)
