### ISSUE TITLE
FFMPEG is not installed

### ISSUE THREAD

**Issue by dazziX** [YTP-Plus/YTPPlusPlus#5]
Everytime I run the program on VS, i keep getting a pop up message saying "FFMPEG is not installed. It may have been misplaced, make sure its in the same directory as YTP++"

I have tried putting both "ffmpeg.exe" and "ffprobe.exe" in the directory but it still doesnt work
Am i doing something wrong here? im so confused
![image](https://user-images.githubusercontent.com/47928800/71820793-355cf400-30cb-11ea-8f90-0e113493a974.png)

Heres the exception message when that happens
![image](https://user-images.githubusercontent.com/47928800/71869645-c1176480-314d-11ea-99f5-3b7555b3c593.png)

And Ive already added ffmpeg to my path

**Comment by TeamPopplio** [comment]
Sorry for not responding sooner. Is FFMPEG in the same directory as the executable?

**Comment by DevanWolf** [comment]
If you are running 32-bit Windows, then download 32-bit FFmpeg from here: https://ffmpeg.zeranoe.com/builds/win32/static/ffmpeg-4.2.3-win32-static.zip

**Comment by KiwifruitDev** [comment]
This repository is no longer supported.
See: [YTP+++](https://github.com/YTP-Plus/YTPPlusPlusPlus)
