### ISSUE TITLE
My videos aren't coming up.

### ISSUE THREAD

**Issue by r-a-z-g-a-r** [YTP-Plus/YTPPlusPlus#6]
After I do everything and I press the 'Render' button, I simply get nothing.

Here are some lines I found on the console that could probably be relevant:
"[NULL @ 00000020eae9c740] Unable to find a suitable output format for 'D:\Program'"
"D:\Program: Invalid argument"

"[concat @ 000000c90a24a200] Value 0.000000 for parameter 'n' out of range [1 - 2.14748e+09]"
"[concat @ 000000c90a24a200] Error setting oprion n to value 0."
"Parsed_concat_0 @ 000000c90a249700] Error initializing filter 'concat' with args 'n=0:v=1:a=1'"
"Error initializing complex filters."
"Result too large."

Is my problem occuring because of any of this? Do you mind explaining to me what this means?

**Comment by TeamPopplio** [comment]
Looks like either ytp++ or a video is in a directory with spaces in it. Try running it directly on the root of your drive or in a folder without any spaces and let me know if that works out.

**Comment by r-a-z-g-a-r** [comment]
I got the problem. My YTP++ folder was in the 'Program Files (x86)' folder, I just had to move it to the root of the drive. Thank you very much!

**Comment by TeamPopplio** [comment]
Glad to hear that!
Closing the issue...
